# TODO: explain it
name: Ardham Tatuaria

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en, pt]

# TODO: explain it
seo_title: ardham-site
meta_keywords: "some meta keywords"
meta_description: "some meta description"
