name: Products
slug: products
description: A description of the content type for the editors
label_field_name: name
order_by: manually # default: manually, also available: created_at or any field slug

fields:
- name: # Name of the field
    label: Name
    type: string
    required: true
    hint: A description of the field for the editors
    localized: false
- photo:
    label: Photo
    type: file
    required: true
    hint: A description of the field for the editors
    localized: false
- category:
    label: Category
    type: belongs_to
    target: categories
